name: brnames
channels:
  - pytorch-nightly
  - nvidia
dependencies:
  - python=3.10.*
  - pytorch
  - pytorch-cuda=11.8
  - pip
  - pip:
      - tqdm
      - rich
      - wandb
      - tensorboard
      - pytorch-lightning
      - ray[tune]
