name: brnames
channels:
  - pytorch-nightly
  - nvidia
dependencies:
  - python=3.11.*
  - pytorch
  - pytorch-cuda=12.1
  - pip
  - pip:
      - tqdm
      - rich
      - wandb
      - tensorboard
      - pytorch-lightning
      - ray[tune]
